routes/web.php
<?php
/**
 * File name: web.php
 * Last modified: 2020.06.07 at 07:02:57
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2020
 *
 */
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');
Auth::routes();
Route::get('storage/app/public/{id}/{conversion}/{filename?}', 'UploadController@storage');
Route::middleware('localeCookieRedirect')->prefix(LaravelLocalization::setLocale())->group(function () {
    Route::get('payments/failed', 'PayPalController@index')->name('payments.failed');
    Route::get('payments/razorpay/checkout', 'RazorPayController@checkout');
    Route::post('payments/razorpay/pay-success/{userId}/{deliveryAddressId?}/{couponCode?}', 'RazorPayController@paySuccess');
    Route::get('payments/razorpay', 'RazorPayController@index');

    Route::get('payments/paypal/express-checkout', 'PayPalController@getExpressCheckout')->name('paypal.express-checkout');
    Route::get('payments/paypal/express-checkout-success', 'PayPalController@getExpressCheckoutSuccess');
    Route::get('payments/paypal', 'PayPalController@index')->name('paypal.index');

    Route::get('firebase/sw-js','AppSettingController@initFirebase');


    Route::middleware('auth')->group(function () {
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::post('uploads/store', 'UploadController@store')->name('medias.create');
        Route::get('users/profile', 'UserController@profile')->name('users.profile');
        Route::post('users/remove-media', 'UserController@removeMedia');
        Route::resource('users', 'UserController');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::group(['middleware' => ['permission:medias']], function () {
            Route::get('uploads/all/{collection?}', 'UploadController@all');
            Route::get('uploads/collectionsNames', 'UploadController@collectionsNames');
            Route::post('uploads/clear', 'UploadController@clear')->name('medias.delete');
            Route::get('medias', 'UploadController@index')->name('medias');
            Route::get('uploads/clear-all', 'UploadController@clearAll');
        });

        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::get('permissions/role-has-permission', 'PermissionController@roleHasPermission');
            Route::get('permissions/refresh-permissions', 'PermissionController@refreshPermissions');
        });
        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::post('permissions/give-permission-to-role', 'PermissionController@givePermissionToRole');
            Route::post('permissions/revoke-permission-to-role', 'PermissionController@revokePermissionToRole');
        });

        Route::group(['middleware' => ['permission:app-settings']], function () {
            Route::prefix('settings')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::resource('roles', 'RoleController');
                Route::resource('customFields', 'CustomFieldController');
                Route::resource('currencies', 'CurrencyController')->except([
                    'show'
                ]);
                Route::get('users/login-as-user/{id}', 'UserController@loginAsUser')->name('users.login-as-user');
                Route::patch('update', 'AppSettingController@update');
                Route::patch('translate', 'AppSettingController@translate');
                Route::get('sync-translation', 'AppSettingController@syncTranslation');
                Route::get('clear-cache', 'AppSettingController@clearCache');
                Route::get('check-update', 'AppSettingController@checkForUpdates');
                // disable special character and number in route params
                Route::get('/{type?}/{tab?}', 'AppSettingController@index')
                    ->where('type', '[A-Za-z]*')->where('tab', '[A-Za-z]*')->name('app-settings');
            });
        });

        Route::post('fields/remove-media','FieldController@removeMedia');
        Route::resource('fields', 'FieldController')->except([
            'show'
        ]);

        Route::post('markets/remove-media', 'MarketController@removeMedia');
        Route::get('requestedMarkets', 'MarketController@requestedMarkets')->name('requestedMarkets.index'); //adeed
        Route::resource('markets', 'MarketController')->except([
            'show'
        ]);

        Route::post('categories/remove-media', 'CategoryController@removeMedia');
        Route::resource('categories', 'CategoryController')->except([
            'show'
        ]);

        Route::resource('faqCategories', 'FaqCategoryController')->except([
            'show'
        ]);

        Route::resource('orderStatuses', 'OrderStatusController')->except([
            'create', 'store', 'destroy'
        ]);;

        Route::post('products/remove-media', 'ProductController@removeMedia');
        Route::resource('products', 'ProductController')->except([
            'show'
        ]);

        Route::post('galleries/remove-media', 'GalleryController@removeMedia');
        Route::resource('galleries', 'GalleryController')->except([
            'show'
        ]);

        Route::resource('productReviews', 'ProductReviewController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');


        Route::resource('payments', 'PaymentController')->except([
            'create', 'store','edit', 'destroy'
        ]);;

        Route::resource('faqs', 'FaqController')->except([
            'show'
        ]);
        Route::resource('marketReviews', 'MarketReviewController')->except([
            'show'
        ]);

        Route::resource('favorites', 'FavoriteController')->except([
            'show'
        ]);

        Route::resource('orders', 'OrderController');

        Route::resource('notifications', 'NotificationController')->except([
            'create', 'store', 'update','edit',
        ]);;

        Route::resource('carts', 'CartController')->except([
            'show','store','create'
        ]);
        Route::resource('deliveryAddresses', 'DeliveryAddressController')->except([
            'show'
        ]);

        Route::resource('drivers', 'DriverController')->except([
            'show'
        ]);

        Route::resource('earnings', 'EarningController')->except([
            'show','edit','update'
        ]);

        Route::resource('driversPayouts', 'DriversPayoutController')->except([
            'show','edit','update'
        ]);

        Route::resource('marketsPayouts', 'MarketsPayoutController')->except([
            'show','edit','update'
        ]);

        Route::resource('optionGroups', 'OptionGroupController')->except([
            'show'
        ]);

        Route::post('options/remove-media','OptionController@removeMedia');

        Route::resource('options', 'OptionController')->except([
            'show'
        ]);
        Route::resource('coupons', 'CouponController')->except([
            'show'
        ]);
        Route::post('slides/remove-media','SlideController@removeMedia');
        Route::resource('slides', 'SlideController')->except([
            'show'
        ]);
    });

});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\OrderRepository;
use App\Repositories\PaymentRepository;
use App\Repositories\MarketRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    /** @var  OrderRepository */
    private $orderRepository;


    /**
     * @var UserRepository
     */
    private $userRepository;

    /** @var  MarketRepository */
    private $marketRepository;
    /** @var  PaymentRepository */
    private $paymentRepository;

    public function __construct(OrderRepository $orderRepo, UserRepository $userRepo, PaymentRepository $paymentRepo, MarketRepository $marketRepo)
    {
        parent::__construct();
        $this->orderRepository = $orderRepo;
        $this->userRepository = $userRepo;
        $this->marketRepository = $marketRepo;
        $this->paymentRepository = $paymentRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ordersCount = $this->orderRepository->count();
        $membersCount = $this->userRepository->count();
        $marketsCount = $this->marketRepository->count();
        $markets = $this->marketRepository->limit(4)->get();
        $earning = $this->paymentRepository->all()->sum('price');
        $ajaxEarningUrl = route('payments.byMonth',['api_token'=>auth()->user()->api_token]);
//        dd($ajaxEarningUrl);
        return view('dashboard.index')
            ->with("ajaxEarningUrl", $ajaxEarningUrl)
            ->with("ordersCount", $ordersCount)
            ->with("marketsCount", $marketsCount)
            ->with("markets", $markets)
            ->with("membersCount", $membersCount)
            ->with("earning", $earning);
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header content-header{{setting('fixed_header')}}">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{trans('lang.dashboard')}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{trans('lang.dashboard')}}</a></li>
                        <li class="breadcrumb-item active">{{trans('lang.dashboard')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{$ordersCount}}</h3>

                        <p>{{trans('lang.dashboard_total_orders')}}</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-shopping-bag"></i>
                    </div>
                    <a href="{!! route('orders.index') !!}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        @if(setting('currency_right', false) != false)
                            <h3>{{$earning}}{{setting('default_currency')}}</h3>
                        @else
                            <h3>{{setting('default_currency')}}{{$earning}}</h3>
                        @endif

                        <p>{{trans('lang.dashboard_total_earnings')}} <span style="font-size: 11px">({{trans('lang.dashboard_after taxes')}})</span></p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-money"></i>
                    </div>
                    <a href="{!! route('payments.index') !!}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{$marketsCount}}</h3>
                        <p>{{trans('lang.market_plural')}}</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-cutlery"></i>
                    </div>
                    <a href="{!! route('markets.index') !!}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>{{$membersCount}}</h3>

                        <p>{{trans('lang.dashboard_total_clients')}}</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-group"></i>
                    </div>
                    <a href="{!! route('users.index') !!}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->

        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header no-border">
                        <div class="d-flex justify-content-between">
                            <h3 class="card-title">{{trans('lang.earning_plural')}}</h3>
                            <a href="{!! route('payments.index') !!}">{{trans('lang.dashboard_view_all_payments')}}</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex">
                            <p class="d-flex flex-column">
                                @if(setting('currency_right', false) != false)
                                    <span class="text-bold text-lg">{{$earning}}{{setting('default_currency')}}</span>
                                @else
                                    <span class="text-bold text-lg">{{setting('default_currency')}}{{$earning}}</span>
                                @endif
                                <span>{{trans('lang.dashboard_earning_over_time')}}</span>
                            </p>
                            <p class="ml-auto d-flex flex-column text-right">
                                <span class="text-success"> {{$ordersCount}}</span></span>
                                <span class="text-muted">{{trans('lang.dashboard_total_orders')}}</span>
                            </p>
                        </div>
                        <!-- /.d-flex -->

                        <div class="position-relative mb-4">
                            <canvas id="sales-chart" height="200"></canvas>
                        </div>

                        <div class="d-flex flex-row justify-content-end">
                            <span class="mr-2"> <i class="fa fa-square text-primary"></i> {{trans('lang.dashboard_this_year')}} </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header no-border">
                        <h3 class="card-title">{{trans('lang.market_plural')}}</h3>
                        <div class="card-tools">
                            <a href="{{route('markets.index')}}" class="btn btn-tool btn-sm"><i class="fa fa-bars"></i> </a>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                            <tr>
                                <th>{{trans('lang.market_image')}}</th>
                                <th>{{trans('lang.market')}}</th>
                                <th>{{trans('lang.market_address')}}</th>
                                <th>{{trans('lang.actions')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($markets as $market)

                                <tr>
                                    <td>
                                        {!! getMediaColumn($market, 'image','img-circle img-size-32 mr-2') !!}
                                    </td>
                                    <td>{!! $market->name !!}</td>
                                    <td>
                                        {!! $market->address !!}
                                    </td>
                                    <td class="text-center">
                                        <a href="{!! route('markets.edit',$market->id) !!}" class="text-muted"> <i class="fa fa-edit"></i> </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('scripts_lib')
    <script src="{{asset('plugins/chart.js/Chart.min.js')}}"></script>
@endpush
@push('scripts')
    <script type="text/javascript">
        var data = [1000, 2000, 3000, 2500, 2700, 2500, 3000];
        var labels = ['JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

        function renderChart(chartNode, data, labels) {
            var ticksStyle = {
                fontColor: '#495057',
                fontStyle: 'bold'
            };

            var mode = 'index';
            var intersect = true;
            return new Chart(chartNode, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [
                        {
                            backgroundColor: '#007bff',
                            borderColor: '#007bff',
                            data: data
                        }
                    ]
                },
                options: {
                    maintainAspectRatio: false,
                    tooltips: {
                        mode: mode,
                        intersect: intersect
                    },
                    hover: {
                        mode: mode,
                        intersect: intersect
                    },
                    legend: {
                        display: false
                    },
                    scales: {
                        yAxes: [{
                            // display: false,
                            gridLines: {
                                display: true,
                                lineWidth: '4px',
                                color: 'rgba(0, 0, 0, .2)',
                                zeroLineColor: 'transparent'
                            },
                            ticks: $.extend({
                                beginAtZero: true,

                                // Include a dollar sign in the ticks
                                callback: function (value, index, values) {
                                    @if(setting('currency_right', '0') == '0')
                                        return "{{setting('default_currency')}} "+value;
                                    @else
                                        return value+" {{setting('default_currency')}}";
                                        @endif

                                }
                            }, ticksStyle)
                        }],
                        xAxes: [{
                            display: true,
                            gridLines: {
                                display: false
                            },
                            ticks: ticksStyle
                        }]
                    }
                }
            })
        }

        $(function () {
            'use strict'

            var $salesChart = $('#sales-chart')
            $.ajax({
                url: "{!! $ajaxEarningUrl !!}",
                success: function (result) {
                    $("#loadingMessage").html("");
                    var data = result.data[0];
                    var labels = result.data[1];
                    renderChart($salesChart, data, labels)
                },
                error: function (err) {
                    $("#loadingMessage").html("Error");
                }
            });
            //var salesChart = renderChart($salesChart, data, labels);
        })

    </script>
@endpush