routes/web.php
<?php
/**
 * File name: web.php
 * Last modified: 2020.06.07 at 07:02:57
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2020
 *
 */
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');
Auth::routes();
Route::get('storage/app/public/{id}/{conversion}/{filename?}', 'UploadController@storage');
Route::middleware('localeCookieRedirect')->prefix(LaravelLocalization::setLocale())->group(function () {
    Route::get('payments/failed', 'PayPalController@index')->name('payments.failed');
    Route::get('payments/razorpay/checkout', 'RazorPayController@checkout');
    Route::post('payments/razorpay/pay-success/{userId}/{deliveryAddressId?}/{couponCode?}', 'RazorPayController@paySuccess');
    Route::get('payments/razorpay', 'RazorPayController@index');

    Route::get('payments/paypal/express-checkout', 'PayPalController@getExpressCheckout')->name('paypal.express-checkout');
    Route::get('payments/paypal/express-checkout-success', 'PayPalController@getExpressCheckoutSuccess');
    Route::get('payments/paypal', 'PayPalController@index')->name('paypal.index');

    Route::get('firebase/sw-js','AppSettingController@initFirebase');


    Route::middleware('auth')->group(function () {
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::post('uploads/store', 'UploadController@store')->name('medias.create');
        Route::get('users/profile', 'UserController@profile')->name('users.profile');
        Route::post('users/remove-media', 'UserController@removeMedia');
        Route::resource('users', 'UserController');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::group(['middleware' => ['permission:medias']], function () {
            Route::get('uploads/all/{collection?}', 'UploadController@all');
            Route::get('uploads/collectionsNames', 'UploadController@collectionsNames');
            Route::post('uploads/clear', 'UploadController@clear')->name('medias.delete');
            Route::get('medias', 'UploadController@index')->name('medias');
            Route::get('uploads/clear-all', 'UploadController@clearAll');
        });

        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::get('permissions/role-has-permission', 'PermissionController@roleHasPermission');
            Route::get('permissions/refresh-permissions', 'PermissionController@refreshPermissions');
        });
        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::post('permissions/give-permission-to-role', 'PermissionController@givePermissionToRole');
            Route::post('permissions/revoke-permission-to-role', 'PermissionController@revokePermissionToRole');
        });

        Route::group(['middleware' => ['permission:app-settings']], function () {
            Route::prefix('settings')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::resource('roles', 'RoleController');
                Route::resource('customFields', 'CustomFieldController');
                Route::resource('currencies', 'CurrencyController')->except([
                    'show'
                ]);
                Route::get('users/login-as-user/{id}', 'UserController@loginAsUser')->name('users.login-as-user');
                Route::patch('update', 'AppSettingController@update');
                Route::patch('translate', 'AppSettingController@translate');
                Route::get('sync-translation', 'AppSettingController@syncTranslation');
                Route::get('clear-cache', 'AppSettingController@clearCache');
                Route::get('check-update', 'AppSettingController@checkForUpdates');
                // disable special character and number in route params
                Route::get('/{type?}/{tab?}', 'AppSettingController@index')
                    ->where('type', '[A-Za-z]*')->where('tab', '[A-Za-z]*')->name('app-settings');
            });
        });

        Route::post('fields/remove-media','FieldController@removeMedia');
        Route::resource('fields', 'FieldController')->except([
            'show'
        ]);

        Route::post('markets/remove-media', 'MarketController@removeMedia');
        Route::get('requestedMarkets', 'MarketController@requestedMarkets')->name('requestedMarkets.index'); //adeed
        Route::resource('markets', 'MarketController')->except([
            'show'
        ]);

        Route::post('categories/remove-media', 'CategoryController@removeMedia');
        Route::resource('categories', 'CategoryController')->except([
            'show'
        ]);

        Route::resource('faqCategories', 'FaqCategoryController')->except([
            'show'
        ]);

        Route::resource('orderStatuses', 'OrderStatusController')->except([
            'create', 'store', 'destroy'
        ]);;

        Route::post('products/remove-media', 'ProductController@removeMedia');
        Route::resource('products', 'ProductController')->except([
            'show'
        ]);

        Route::post('galleries/remove-media', 'GalleryController@removeMedia');
        Route::resource('galleries', 'GalleryController')->except([
            'show'
        ]);

        Route::resource('productReviews', 'ProductReviewController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');


        Route::resource('payments', 'PaymentController')->except([
            'create', 'store','edit', 'destroy'
        ]);;

        Route::resource('faqs', 'FaqController')->except([
            'show'
        ]);
        Route::resource('marketReviews', 'MarketReviewController')->except([
            'show'
        ]);

        Route::resource('favorites', 'FavoriteController')->except([
            'show'
        ]);

        Route::resource('orders', 'OrderController');

        Route::resource('notifications', 'NotificationController')->except([
            'create', 'store', 'update','edit',
        ]);;

        Route::resource('carts', 'CartController')->except([
            'show','store','create'
        ]);
        Route::resource('deliveryAddresses', 'DeliveryAddressController')->except([
            'show'
        ]);

        Route::resource('drivers', 'DriverController')->except([
            'show'
        ]);

        Route::resource('earnings', 'EarningController')->except([
            'show','edit','update'
        ]);

        Route::resource('driversPayouts', 'DriversPayoutController')->except([
            'show','edit','update'
        ]);

        Route::resource('marketsPayouts', 'MarketsPayoutController')->except([
            'show','edit','update'
        ]);

        Route::resource('optionGroups', 'OptionGroupController')->except([
            'show'
        ]);

        Route::post('options/remove-media','OptionController@removeMedia');

        Route::resource('options', 'OptionController')->except([
            'show'
        ]);
        Route::resource('coupons', 'CouponController')->except([
            'show'
        ]);
        Route::post('slides/remove-media','SlideController@removeMedia');
        Route::resource('slides', 'SlideController')->except([
            'show'
        ]);
    });

});

app/Http/Controllers/PermissionController.php
<?php
/**
 * File name: PermissionController.php
 * Last modified: 2020.06.03 at 20:04:43
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2020
 *
 */

namespace App\Http\Controllers;

use App\DataTables\PermissionDataTable;
use App\Http\Requests;
use App\Http\Requests\CreatePermissionRequest;
use App\Http\Requests\UpdatePermissionRequest;
use App\Repositories\PermissionRepository;
use Flash;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Artisan;
use Request;
use Response;

class PermissionController extends Controller
{
    /** @var  PermissionRepository */
    private $permissionRepository;

    public function __construct(PermissionRepository $permissionRepo)
    {
        parent::__construct();
        $this->permissionRepository = $permissionRepo;
    }

    /**
     * Display a listing of the Permission.
     *
     * @param PermissionDataTable $permissionDataTable
     * @return Response
     */
    public function index(PermissionDataTable $permissionDataTable)
    {
        return $permissionDataTable->render('settings.permissions.index');
    }

    public function refreshPermissions(Request $request){
        Artisan::call('db:seed',['--class'=> 'DemoPermissionsPermissionsTableSeeder']);
        redirect()->back();
    }

    public function givePermissionToRole(Request $request){
        if(env('APP_DEMO',false)) {
            Flash::warning('This is only demo app you can\'t change this section ');
        }else{
            $input = Request::all();
            $this->permissionRepository->givePermissionToRole($input);
        }
    }

    public function revokePermissionToRole(Request $request){
        if(env('APP_DEMO',false)) {
            Flash::warning('This is only demo app you can\'t change this section ');
        }else{
            $input = Request::all();
            $this->permissionRepository->revokePermissionToRole($input);
        }
    }

    public function roleHasPermission(Request $request){
        $input = Request::all();
        //dd($input);
        $result = $this->permissionRepository->roleHasPermission($input);
        return json_encode($result);
    }


    /**
     * Show the form for creating a new Permission.
     *
     * @return Response
     */
    public function create()
    {
        return view('settings.permissions.create');
    }

    /**
     * Store a newly created Permission in storage.
     *
     * @param CreatePermissionRequest $request
     *
     * @return Response
     */
    public function store(CreatePermissionRequest $request)
    {
        if(env('APP_DEMO',false)) {
            Flash::warning('This is only demo app you can\'t change this section ');
            return redirect(route('permissions.index'));
        }
        $input = $request->all();

        $permission = $this->permissionRepository->create($input);

        Flash::success('Permission saved successfully.');

        return redirect(route('permissions.index'));
    }

    /**
     * Display the specified Permission.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $permission = $this->permissionRepository->findWithoutFail($id);

        if (empty($permission)) {
            Flash::error('Permission not found');

            return redirect(route('permissions.index'));
        }

        return view('settings.permissions.show')->with('permission', $permission);
    }

    /**
     * Show the form for editing the specified Permission.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $permission = $this->permissionRepository->findWithoutFail($id);

        if (empty($permission)) {
            Flash::error('Permission not found');

            return redirect(route('permissions.index'));
        }

        return view('settings.permissions.edit')->with('permission', $permission);
    }

    /**
     * Update the specified Permission in storage.
     *
     * @param  int              $id
     * @param UpdatePermissionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePermissionRequest $request)
    {
        if(env('APP_DEMO',false)) {
            Flash::warning('This is only demo app you can\'t change this section ');
            return redirect(route('permissions.index'));
        }
        $permission = $this->permissionRepository->findWithoutFail($id);

        if (empty($permission)) {
            Flash::error('Permission not found');

            return redirect(route('permissions.index'));
        }

        $permission = $this->permissionRepository->update($request->all(), $id);

        Flash::success('Permission updated successfully.');

        return redirect(route('permissions.index'));
    }

    /**
     * Remove the specified Permission from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        if(env('APP_DEMO',false)) {
            Flash::warning('This is only demo app you can\'t change this section ');
            return redirect(route('permissions.index'));
        }
        $permission = $this->permissionRepository->findWithoutFail($id);

        if (empty($permission)) {
            Flash::error('Permission not found');

            return redirect(route('permissions.index'));
        }

        $this->permissionRepository->delete($id);

        Flash::success('Permission deleted successfully.');

        return redirect(route('permissions.index'));
    }
}

resources/views/settings/permissions/create.blade.php
@extends('layouts.settings.default')
@push('css_lib')
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- select2 -->
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
@endpush
@section('settings_title',trans('lang.permission_create'))
@section('settings_content')
    @include('adminlte-templates::common.errors')
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('permissions.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.permission_table')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{!! route('permissions.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.permission_create')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('roles.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.role_table')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('roles.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.role_create')}}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            {!! Form::open(['route' => 'permissions.store']) !!}
            <div class="row">
                @include('settings.permissions.fields')
            </div>
            {!! Form::close() !!}
            <div class="clearfix"></div>
        </div>
    </div>
@endsection
@push('scripts_lib')
    <!-- iCheck -->
    <script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
    <!-- select2 -->
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
@endpush

resources/views/settings/permissions/datatables_actions.blade.php
<div class='btn-group btn-group-sm'>
    @can('permissions.edit')
        <a href="{{ route('permissions.edit', $id) }}" class='btn btn-link'> <i class="fa fa-edit"></i> </a>
    @endcan
    @can('permissions.destroy')
        {!! Form::open(['route' => ['permissions.destroy', $id], 'method' => 'delete']) !!}
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-link text-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
{!! Form::close() !!}
    @endcan
</div>

resources/views/settings/permissions/edit.blade.php
@extends('layouts.settings.default')
@push('css_lib')
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- select2 -->
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
@endpush
@section('settings_title',trans('lang.permission_edit'))
@section('settings_content')
    @include('adminlte-templates::common.errors')
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('permissions.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.permission_table')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{!! route('permissions.edit',$permission->id) !!}"><i class="fa fa-pencil mr-2"></i>{{trans('lang.permission_edit')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('roles.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.role_table')}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('roles.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.role_create')}}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            {!! Form::model($permission, ['route' => ['permissions.update', $permission->id], 'method' => 'patch']) !!}
            <div class="row">
                @include('settings.permissions.fields')
            </div>
            {!! Form::close() !!}
            <div class="clearfix"></div>
        </div>
    </div>
@endsection
@push('scripts_lib')
    <!-- iCheck -->
    <script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
    <!-- select2 -->
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
@endpush

resources/views/settings/permissions/fields.blade.php
<!-- Name Field -->
<div class="form-group row col-6">
    {!! Form::label('name', 'Name:', ['class' => 'col-3 control-label text-right']) !!}
    <div class="col-9">
        {!! Form::text('name', null, ['class' => 'form-control','placeholder'=>trans("lang.permission_name_placeholder")]) !!}
        <small class="form-text text-muted">
            {{trans("lang.permission_name_help")}}
        </small>
    </div>
</div>

<!-- Guard Name Field -->
<div class="form-group row col-6">
    {!! Form::label('guard_name', 'Guard Name:', ['class' => 'col-3 control-label text-right']) !!}
    <div class="col-9">
        {!! Form::text('guard_name', null, ['class' => 'form-control','placeholder'=>
        (Lang::has("lang.permission_name_placeholder")) ? trans("lang.permission_guard_name_placeholder") : "Name guard_name"]) !!}
        <small class="form-text text-muted">
            {{(Lang::has("lang.permission_guard_name_help")) ? trans("lang.permission_guard_name_help") : "Insert the guard_name"}}
        </small>
    </div>
</div>
<!-- Submit Field -->
<div class="form-group col-sm-12 text-right">
    <button type="submit" class="btn btn-{{setting('theme_color')}}"><i class="fa fa-save"></i> {{trans('lang.save')}} {{trans('lang.permission')}}</button>
    <a href="{!! route('permissions.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> {{trans('lang.cancel')}}</a>
</div>

resources/views/settings/permissions/index.blade.php
@extends('layouts.settings.default')
@push('css_lib')
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
@endpush
@section('settings_title',trans('lang.permission_table'))

@section('settings_content')
    @include('flash::message')
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                <li class="nav-item">
                    <a class="nav-link active" href="{!! route('permissions.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.permission_table')}}</a>
                </li>
                @can('permissions.create')
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('permissions.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.permission_create')}}</a>
                </li>
                @endcan
                @can('roles.index')
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('roles.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.role_table')}}</a>
                </li>
                @endcan
                @can('roles.create')
                <li class="nav-item">
                    <a class="nav-link" href="{!! route('roles.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.role_create')}}</a>
                </li>
                @endcan

                @include('layouts.right_toolbar', compact('dataTable'))
            </ul>
        </div>
        <div class="card-body">
            @include('settings.permissions.table')
            <div class="clearfix"></div>
        </div>
    </div>
@endsection
@push('scripts_lib')
    <!-- iCheck -->
    <script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
@endpush

resources/views/settings/permissions/table.blade.php
@push('css_lib')
    @include('layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts_lib')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush